name: book
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_mobile_ads: ^5.2.0
  gdpr_admob: ^1.0.1
  http: ^1.2.1
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.4


  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Scala
      fonts:
        - asset: fonts/scala-sans.ttf
        - asset: fonts/scala.ttf
    - family: Din Offc Pro
      fonts:
        - asset: fonts/din-offc-pro.ttf
        - asset: fonts/din-offc-pro-b.ttf
        - asset: fonts/din-offc-pro-bi.ttf
        - asset: fonts/din-offc-pro-i.ttf
        - asset: fonts/din-offc-pro-medium-sc.ttf
        - asset: fonts/din-offc-pro-medium-i-sc.ttf
    - family: Harriet Text
      fonts:
        - asset: fonts/harriet-text.ttf
        - asset: fonts/harriet-text-sc.ttf
        - asset: fonts/harriet-text-b.ttf
        - asset: fonts/harriet-text-b-sc.ttf
        - asset: fonts/harriet-text-bi.ttf
        - asset: fonts/harriet-text-bi-sc.ttf
        - asset: fonts/harriet-text-i.ttf
        - asset: fonts/harriet-text-i-sc.ttf
    - family: Scala Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Bold.ttf
        - asset: fonts/SourceSansPro-BoldItalic.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Semibold.ttf
        - asset: fonts/SourceSansPro-SemiboldItalic.ttf
    - family: Tisa Offc Pro
      fonts:
        - asset: fonts/tisa-offc-pro.ttf
        - asset: fonts/tisa-offc-pro-b.ttf
        - asset: fonts/tisa-offc-pro-bi.ttf
        - asset: fonts/tisa-offc-pro-i.ttf
    - family: Tisa SC Offc Pro
      fonts:
        - asset: fonts/tisa-sc-offc-pro.ttf
        - asset: fonts/tisa-sc-offc-pro-b.ttf
        - asset: fonts/tisa-sc-offc-pro-bi.ttf
        - asset: fonts/tisa-sc-offc-pro-i.ttf
    - family: Vollkorn
      fonts:
        - asset: fonts/vollkorn.ttf
        - asset: fonts/vollkorn-b.ttf
        - asset: fonts/vollkorn-bi.ttf
        - asset: fonts/vollkorn-i.ttf
    - family: Livory
      fonts:
        - asset: fonts/livory-bi.ttf
        - asset: fonts/livory-i.ttf
        - asset: fonts/livory-sc.ttf
    #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
